### ISSUE TITLE
Tagging latest version

### ISSUE THREAD

**Issue by rinigus** [almindor/lighthouse#29]
I have added Lighthouse to OBS Chum testing repository. All looks to be fine and the install works for the combination that I can test. See builds at https://build.sailfishos.org/package/show/sailfishos:chum:testing/lighthouse

@almindor: If you could tag the current version in a form `v1.6.6` (seems you use that notation in GitHub releases), I would be able to use that tag in OBS service file and RPMs produced will have that version. Right now, users will be installing RPM with version set to 

`1.6.5+master.20220107212046.3.g223ccff`

as OBS sets the version based on the used commit tag and, if none, then adds branch-date-commit to the version.

**Comment by almindor** [comment]
Created [v1.6.6](https://github.com/almindor/lighthouse/releases/tag/v1.6.6)

**Comment by rinigus** [comment]
Thank you very much, rebuilding with this tag. Will be published in Chum in few minutes
