### ISSUE TITLE
[not-a-issue]Chinese Translation for the Description in Jolla Store

### ISSUE THREAD

**Issue by TylerTemp** [almindor/lighthouse#6]
Really love this app XD

Since Jolla Store supports Chinese description according to this [answer](https://together.jolla.com/question/79317/store-app-description-translation-support/), I'd appreciate if you can put the Chinese description too :-). Hope it can help more Chinese people know this helpful app ;-)

Here is the Chinese translation:

* * * * * * 

> Lighthouse is a system monitor application for SailfishOS.

Lighthouse是一款旗鱼操作系统的系统监控软件。

> Lighthouse is a system monitor application for SailfishOS.

Lighthouse是一款旗鱼操作系统的系统监控软件。

> Currently supported views are system CPU and memory usage, process list and additionally phone controls to reboot and shut down the phone.

目前支持查看系统CPU、内存用量、进程列表，以及额外的手机重启和关机控制。

**Comment by almindor** [comment]
Hey thanks for the translation!

Could you please use transifex to submit the file? You can find the project at ﻿﻿https://www.transifex.com/projects/p/lighthouse/ I forgot to put this info in the readme/info sections (doing that now).

Thanks!
