### ISSUE TITLE
Several transifex strings need context

### ISSUE THREAD

**Issue by hobarrera** [almindor/lighthouse#8]
Several strings need context in order to translate to some languages.

For example, some strings say "Unknown". According to what this refers to, the translation varies. To further this example, in spanish songs are feminine, while albums are masculine, so one is "Desconocid**o**" and the other "Desconocid**a**".

I marked these with comments a long while ago, but I noticed there's still no context.

**Comment by almindor** [comment]
Hmm I added comments to some of the generic strings, I guess I missed these. Will look into it.

**Comment by hobarrera** [comment]
Thanks. Mostly it was several instances of "Unknown".

**Comment by almindor** [comment]
This should hopefully be fixed. If not please use transifex for translation issue reporting.
