### ISSUE TITLE
a small bug ))

### ISSUE THREAD

**Issue by lewadedun** [almindor/lighthouse#9]
Word is not included in the string )
![20150602215319](https://cloud.githubusercontent.com/assets/9382415/7942365/2f177e06-0977-11e5-8eef-d91be2eccb2d.jpg)

**Comment by almindor** [comment]
This is a translation issue. You can help by going to transifex and
changing the wording to be shorter.

**Comment by lewadedun** [comment]
I updated the translation ))

**Comment by almindor** [comment]
Thanks! I'll put it up with the next release

**Comment by almindor** [comment]
Should now be updated
